### PR TITLE
Helper functions for rdm discovery response

### PR DESCRIPTION
**Pull request by arneboe**
I added some helper functions that I need to make the device discoverable via RDM.

The example was tested using the "Botex Dr. RDM | DMX RDM Tester" and it works.

Do you think it would make sense to add basic rdm stuff like discovery, getting/setting the dmx address etc. directly to the
esp_dmx.h? Imo there is no need for the user to implement the basic stuff himself.

### CODE REVIEW

**Comment by arneboe** [comment]
Hmm okay, the more I read your code and try to add stuff, the more I think that this PR is not the way to go :D
I'll leave it open for now because I am still adding stuff and experimenting with rdm but I don't think this should be merged.
Probably I'll rewrite everything once I have an rdm prototype working

**Comment by someweisguy** [comment]
Yeah, I agree. I apologize - I'm not exactly making it easy to submit pull requests. I've been making all my changes on the v3 branch pretty quickly lately. Just yesterday I renamed the `dmx_event_t` type to `dmx_packet_t` so I imagine that will mess up anything you've worked on so far. I will start working in the dev branch and merging features moving forward.

A little background about where the state of this repo stands right now: I believe that the RDM controller works. I've implemented the the minimum required RDM parameters. The list of those can be found [in the readme](https://github.com/someweisguy/esp_dmx/tree/release/v3.0#parameters). I've also implemented RDM discovery so that end-users don't need to worry about that. I'll add some discovery example code today (Edit: it's been [added](https://github.com/someweisguy/esp_dmx/tree/release/v3.0/examples/idf_rdm_discovery)). The other examples have been updated for v3, so perhaps that will help to take a look at. 

The next big hurdle is implementing the DMX responder. I am not exactly sure what that will look like. Based on the feedback I've gotten, most people that use this library are hobbyists. So I've really been trying to strike a balance between usability for the newbies still learning how DMX/RDM works, and powerful features for the professionals who are actually using this library to create a product. To that end, I'm envisioning an `rdm_reply()` function that users can call which will parse an RDM request and automatically send responses. Users can then attach callbacks to the RDM driver so that when the ESP32 receives a SET `DMX_START_ADDRESS` request, the ESP32 can run the callback which will set the start address appropriately and then it will send an ACK back to the RDM controller, or a NACK if the callback returns some other value.

Before that, I'm working on documentation. After documentation is squared away, I'm thinking about releasing a v3.0-beta to get some more people testing the library while working on implementing the RDM responder.

**Comment by someweisguy** [comment]
Yeah, I agree. I apologize - I'm not exactly making it easy to submit pull requests. I've been making all my changes on the v3 branch pretty quickly lately. Just yesterday I renamed the `dmx_event_t` type to `dmx_packet_t` so I imagine that will mess up anything you've worked on so far. I will start working in the dev branch and merging features moving forward.

A little background about where the state of this repo stands right now: I believe that the RDM controller works. I've implemented the the minimum required RDM parameters. The list of those can be found [in the readme](https://github.com/someweisguy/esp_dmx/tree/release/v3.0#parameters). I've also implemented RDM discovery so that end-users don't need to worry about that. I'll add some discovery example code today. The other examples have been updated for v3, so perhaps that will help to take a look at. 

The next big hurdle is implementing the DMX responder. I am not exactly sure what that will look like. Based on the feedback I've gotten, most people that use this library are hobbyists. So I've really been trying to strike a balance between usability for the newbies still learning how DMX/RDM works, and powerful features for the professionals who are actually using this library to create a product. To that end, I'm envisioning an `rdm_reply()` function that users can call which will parse an RDM request and automatically send responses. Users can then attach callbacks to the RDM driver so that when the ESP32 receives a SET `DMX_START_ADDRESS` request, the ESP32 can run the callback which will set the start address appropriately and then it will send an ACK back to the RDM controller, or a NACK if the callback returns some other value.

Before that, I'm working on documentation. After documentation is squared away, I'm thinking about releasing a v3.0-beta to get some more people testing the library while working on implementing the RDM responder.

**Comment by arneboe** [comment]
> Yeah, I agree. I apologize - I'm not exactly making it easy to submit pull requests. I've been making all my changes on the v3 branch pretty quickly lately. Just yesterday I renamed the `dmx_event_t` type to `dmx_packet_t` so I imagine that will mess up anything you've worked on so far. I will start working in the dev branch and merging features moving forward.

Don't worry, I am used to developing in fast moving systems :) Renaming took less than 30 seconds :D
I really like, that you are implementing features this fast. I know, that whatever I implement will be obsolete within weeks and I am fine with that :)


> The next big hurdle is implementing the DMX responder. I am not exactly sure what that will look like. Based on the feedback I've gotten, most people that use this library are hobbyists. So I've really been trying to strike a balance between usability for the newbies still learning how DMX/RDM works, and powerful features for the professionals who are actually using this library to create a product. To that end, I'm envisioning an `rdm_reply()` function that users can call which will parse an RDM request and automatically send responses. Users can then attach callbacks to the RDM driver so that when the ESP32 receives a SET `DMX_START_ADDRESS` request, the ESP32 can run the callback which will set the start address appropriately and then it will send an ACK back to the RDM controller, or a NACK if the callback returns some other value.

I was thinking the same thing and have started implementing a very crude first test version in [32c2495](https://github.com/someweisguy/esp_dmx/pull/32/commits/32c24950a5f3b73bcf87a0ce35fa311da9419da7). This is still in the tinkering phase and will likely remain there far longer than it would take you to implement it correctly because my time is limited due to work :(

Imo it could be nice to implement a parameter-object server that supports all standard objects and allows for the addition of custom user specified objects. The dmx responder would have access to the parameter server and can forward get/set calls.
In the parameter server you can attach custom callbacks to the objects to get notifications when something changes.
This is a concept that I see often in all kinds of industrial field bus systems (e.g. canOpen, Ethernet/IP, Profinet) and it seems to work well. I may start to implement something along those lines in December maybe :)

**Comment by someweisguy** [comment]
>Imo it could be nice to implement a parameter-object server that supports all standard objects and allows for the addition of custom user specified objects. The dmx responder would have access to the parameter server and can forward get/set calls.
In the parameter server you can attach custom callbacks to the objects to get notifications when something changes.
This is a concept that I see often in all kinds of industrial field bus systems (e.g. canOpen, Ethernet/IP, Profinet) and it seems to work well. I may start to implement something along those lines in December maybe :)

This sounds excellent! I may get a head start on you, but we will see. I have a feeling chasing bugs in the RDM controller code is going to slow me down. :)

In the meantime, I'll close this pull request. Thank you!

**Pull request closed without merging**
